### ISSUE TITLE
Weird looking Interface

### ISSUE THREAD

**Issue by cptpiepmatz** [rom1504/MinecraftChat#13]
Hey, I would really like to use your Webchat here but i got only a weird interface when I install and run your app.

![Error Image](https://drive.google.com/uc?export=download&id=1Qou3C4bgslJqjj7Blh7vKpVswOnzZlsk)

```
derPi@TimsTower MINGW64 /d/Code_Test/MinecraftChat (master)
$ yarn install
yarn install v1.9.2
info No lockfile found.
[1/4] Resolving packages...
warning babel > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2
 or higher to avoid a RegExp DoS issue
warning grunt > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to
 avoid a RegExp DoS issue
warning grunt > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or hi
gher to avoid a RegExp DoS issue
warning grunt > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for c
ompatibility with current and future versions of Node.js
warning grunt > coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeesc
ript" (no hyphen)
warning grunt > findup-sync > glob > minimatch@0.3.0: Please update to minimatc
h 3.0.2 or higher to avoid a RegExp DoS issue
warning grunt-browserify > browserify > glob > minimatch@2.0.10: Please update
to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning grunt-contrib-watch > gaze > globule > minimatch@0.2.14: Please update
to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gruntify-eslint > eslint > minimatch@2.0.10: Please update to minimatch
 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
 Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 21.28s.

derPi@TimsTower MINGW64 /d/Code_Test/MinecraftChat (master)
$ grunt build
Running "browserify:pro" (browserify) task
>> Bundle public/js/app.js created.

Running "uglify:target" (uglify) task
>> 1 file created.

Done, without errors.

derPi@TimsTower MINGW64 /d/Code_Test/MinecraftChat (master)
$ yarn start
yarn run v1.9.2
$ node bin/start
{ Error: ENOENT: no such file or directory, open 'D:\Code_Test\MinecraftChat\.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.config (D:\Code_Test\MinecraftChat\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (D:/Code_Test/MinecraftChat/app/server/index.js:17:8)    at Module._compile (module.js:65
2:30)
    at normalLoader (D:\Code_Test\MinecraftChat\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Code_Test\MinecraftChat\node_modules\babel-core\
lib\api\register\node.js:216:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Code_Test\\MinecraftChat\\.env' }
> Server running on port 3000
```

**Comment by Threnklyn** [comment]
It just complains that it does not find the .env file. there you can define the port on which the server will be accessible.
I have [forked](https://github.com/Kuchenm0nster/MinecraftChat) MinecraftChat and added support for the newer Minecraft versions. It also fixes the display error (css)
