### ISSUE TITLE
Interface not working anymore

### ISSUE THREAD

**Issue by Paralusion** [rom1504/MinecraftChat#14]
https://i.imgur.com/RVdXqe6.png
I can connect to a server, chat, but can not read chat as said.

**Comment by TheIdealMatrix** [comment]
Same for me but i can't do anything, and i get an Error in the Console:

C:\Users\Kevin\Desktop\MinecraftChat>npm start

> MinecraftChat@1.0.0 start C:\Users\Kevin\Desktop\MinecraftChat
> node bin/start

Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at Object.config (C:\Users\Kevin\Desktop\MinecraftChat\node_modules\dotenv\lib\main.js:30:37)
    at Object.<anonymous> (C:/Users/Kevin/Desktop/MinecraftChat/app/server/index.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at normalLoader (C:\Users\Kevin\Desktop\MinecraftChat\node_modules\babel-core\lib\api\register\node.js:199:5)
    at Object.require.extensions.<computed> [as .js] (C:\Users\Kevin\Desktop\MinecraftChat\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}
> Server running on port 3000

**Comment by Threnklyn** [comment]
I have [forked](https://github.com/Kuchenm0nster/MinecraftChat) MinecraftChat and added support for the newer Minecraft versions. It also fixes the display error

**Comment by rom1504** [comment]
Feel free to PR
