### ISSUE TITLE
Help Error

### ISSUE THREAD

**Issue by TheIdealMatrix** [rom1504/MinecraftChat#15]
pi@raspberrypi:~/MinecraftChat $ npm start
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> MinecraftChat@1.0.0 start /home/pi/MinecraftChat
> node bin/start

{ Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.config (/home/pi/MinecraftChat/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/home/pi/MinecraftChat/app/server/index.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at normalLoader (/home/pi/MinecraftChat/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pi/MinecraftChat/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) errno: -2, syscall: 'open', code: 'ENOENT', path: '.env' }
> Server running on port 3000

**Comment by Threnklyn** [comment]
It just complains that it does not find the .env file. there you can define the port on which the server will be accessible.
I have [forked](https://github.com/Kuchenm0nster/MinecraftChat) MinecraftChat and added support for the newer Minecraft versions
